### ISSUE TITLE
TypeError: Class constructor AbstractMessageReader cannot be invoked without 'new'

### ISSUE THREAD

**Issue by felixfbecker** [TypeFox/vscode-ws-jsonrpc#8]
`vscode-ws-jsonrpc` uses `target: es5`, which transpiles classes to functions. But `vscode-jsonrpc` uses `target: es6`, which does not transpile classes. Therefor classes that inherit from classes in `vscode-jsonrpc` error when trying to instantiate them.

**Comment by netweng** [comment]
i do this locally and compile the vscode-jsonrpc to es6, it did solved my problem. and i just wander when this pr can be merged into master, and vscod-jsonrpc can update its version? otherwise i need to compile it by myself and use unofficial package

**Comment by lilliesAndRoses** [comment]
The node_modules folder that I have installed for vscode-ws-jsonrpc does not have a tsconfig.json.
I need to use the monaco language client in a 'webpack'ed environment and I am stuck with this error.
How do I get around?

**Comment by felixfbecker** [comment]
I published `@sourcegraph/vscode-ws-jsonrpc` with a fix for this

**Comment by lilliesAndRoses** [comment]
I wanted to do this fix in my local environment if it is simple enough. I do not see the tsconfig.json in either vscode-ws-jsonrpc or in vscode-jsonrpc.
Does this indicate something wrong in the first place?

**Comment by felixfbecker** [comment]
I don't understand what you mean by that - tsconfig.jsons are generally never published to npm, but they do exist in the source repos you mentioned.

**Comment by lilliesAndRoses** [comment]
Oh. That is why I need to use your repo. I get it. Thanks. I have not used NPM modules that were typescript based before, hence the doubt. Thanks for the clarification.

**Comment by netweng** [comment]
> I published `@sourcegraph/vscode-ws-jsonrpc` with a fix for this

thanks

**Comment by akosyakov** [comment]
latest is points now to 0.1.1 which is transpiled to es6
